# Definition
SERIAL_PORT_TIMEOUT_ROUTER = 1000
SERIAL_PORT_TIMEOUT_ENDDEVICE = 10000

HA_PROFILE_ID = 0x0104
ZLL_PROFILE_ID = 0xC05E

PERMIT_JOIN_DURATION = 0xF0
PERMIT_JOIN_NO_TIME_LIMIT = 0xFF
PERMIT_JOIN_STOP = 0x00

DEFAULT_CHANNEL = 0x14

TOTAL_TEST_DEVICES = 25
LOOP_COUNTS = 1500
TOTAL_TEST_COUNTS = TOTAL_TEST_DEVICES * LOOP_COUNTS

DEVICE_LIST_FILENAME = "devicelist.txt"